/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicBookRouteImport } from './routes/_public.book'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicCreateAccountRouteImport } from './routes/_public.create-account'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public.forgot-password'
import { Route as PublicHowItWorksRouteImport } from './routes/_public.how-it-works'
import { Route as PublicMenuRouteImport } from './routes/_public.menu'
import { Route as PublicOurStoryRouteImport } from './routes/_public.our-story'
import { Route as PublicPoliciesRouteImport } from './routes/_public.policies'
import { Route as PublicPrivateRoomRouteImport } from './routes/_public.private-room'
import { Route as PublicResetPasswordRouteImport } from './routes/_public.reset-password'
import { Route as PublicSignInRouteImport } from './routes/_public.sign-in'
import { Route as PublicTheExperienceRouteImport } from './routes/_public.the-experience'
import { Route as PublicWaitlistRouteImport } from './routes/_public.waitlist'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountPaymentsRouteImport } from './routes/account.payments'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountReservationsRouteImport } from './routes/account.reservations'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminDiscountsRouteImport } from './routes/admin.discounts'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMenuItemsRouteImport } from './routes/admin.menu-items'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPrivateRoomRouteImport } from './routes/admin.private-room'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSeatingTimesRouteImport } from './routes/admin.seating-times'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSundaysRouteImport } from './routes/admin.sundays'
import { Route as AdminTablesRouteImport } from './routes/admin.tables'
import { Route as AdminTaxesRouteImport } from './routes/admin.taxes'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as KitchenIndexRouteImport } from './routes/kitchen.index'
import { Route as KitchenDietaryNotesRouteImport } from './routes/kitchen.dietary-notes'
import { Route as KitchenMealTotalsRouteImport } from './routes/kitchen.meal-totals'
import { Route as KitchenPreparationRouteImport } from './routes/kitchen.preparation'
import { Route as KitchenReportsRouteImport } from './routes/kitchen.reports'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffCalendarRouteImport } from './routes/staff.calendar'
import { Route as StaffCheckInRouteImport } from './routes/staff.check-in'
import { Route as StaffCommunicationsRouteImport } from './routes/staff.communications'
import { Route as StaffGuestRequestsRouteImport } from './routes/staff.guest-requests'
import { Route as StaffReservationsRouteImport } from './routes/staff.reservations'
import { Route as StaffSeatingRouteImport } from './routes/staff.seating'
import { Route as StaffWaitlistRouteImport } from './routes/staff.waitlist'
import { Route as StaffWalkInsRouteImport } from './routes/staff.walk-ins'
import { Route as PublicAuthCallbackRouteImport } from './routes/_public.auth.callback'
import { Route as AccountReservationsIndexRouteImport } from './routes/account.reservations.index'
import { Route as AccountReservationsReservationIdRouteImport } from './routes/account.reservations.$reservationId'
import { Route as StaffReservationsIndexRouteImport } from './routes/staff.reservations.index'
import { Route as StaffReservationsReservationIdRouteImport } from './routes/staff.reservations.$reservationId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookRoute = PublicBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCreateAccountRoute = PublicCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHowItWorksRoute = PublicHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMenuRoute = PublicMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOurStoryRoute = PublicOurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPoliciesRoute = PublicPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivateRoomRoute = PublicPrivateRoomRouteImport.update({
  id: '/private-room',
  path: '/private-room',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTheExperienceRoute = PublicTheExperienceRouteImport.update({
  id: '/the-experience',
  path: '/the-experience',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWaitlistRoute = PublicWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => PublicRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReservationsRoute = AccountReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuItemsRoute = AdminMenuItemsRouteImport.update({
  id: '/menu-items',
  path: '/menu-items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrivateRoomRoute = AdminPrivateRoomRouteImport.update({
  id: '/private-room',
  path: '/private-room',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeatingTimesRoute = AdminSeatingTimesRouteImport.update({
  id: '/seating-times',
  path: '/seating-times',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSundaysRoute = AdminSundaysRouteImport.update({
  id: '/sundays',
  path: '/sundays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxesRoute = AdminTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenDietaryNotesRoute = KitchenDietaryNotesRouteImport.update({
  id: '/dietary-notes',
  path: '/dietary-notes',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenMealTotalsRoute = KitchenMealTotalsRouteImport.update({
  id: '/meal-totals',
  path: '/meal-totals',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenPreparationRoute = KitchenPreparationRouteImport.update({
  id: '/preparation',
  path: '/preparation',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenReportsRoute = KitchenReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => KitchenRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCalendarRoute = StaffCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCheckInRoute = StaffCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCommunicationsRoute = StaffCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffGuestRequestsRoute = StaffGuestRequestsRouteImport.update({
  id: '/guest-requests',
  path: '/guest-requests',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReservationsRoute = StaffReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSeatingRoute = StaffSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => StaffRoute,
} as any)
const StaffWaitlistRoute = StaffWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => StaffRoute,
} as any)
const StaffWalkInsRoute = StaffWalkInsRouteImport.update({
  id: '/walk-ins',
  path: '/walk-ins',
  getParentRoute: () => StaffRoute,
} as any)
const PublicAuthCallbackRoute = PublicAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const AccountReservationsIndexRoute =
  AccountReservationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountReservationsRoute,
  } as any)
const AccountReservationsReservationIdRoute =
  AccountReservationsReservationIdRouteImport.update({
    id: '/$reservationId',
    path: '/$reservationId',
    getParentRoute: () => AccountReservationsRoute,
  } as any)
const StaffReservationsIndexRoute = StaffReservationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffReservationsRoute,
} as any)
const StaffReservationsReservationIdRoute =
  StaffReservationsReservationIdRouteImport.update({
    id: '/$reservationId',
    path: '/$reservationId',
    getParentRoute: () => StaffReservationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/kitchen': typeof KitchenRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/book': typeof PublicBookRoute
  '/contact': typeof PublicContactRoute
  '/create-account': typeof PublicCreateAccountRoute
  '/faq': typeof PublicFaqRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/menu': typeof PublicMenuRoute
  '/our-story': typeof PublicOurStoryRoute
  '/policies': typeof PublicPoliciesRoute
  '/private-room': typeof PublicPrivateRoomRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/the-experience': typeof PublicTheExperienceRoute
  '/waitlist': typeof PublicWaitlistRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRouteWithChildren
  '/account/support': typeof AccountSupportRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu-items': typeof AdminMenuItemsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/private-room': typeof AdminPrivateRoomRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seating-times': typeof AdminSeatingTimesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sundays': typeof AdminSundaysRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/admin/users': typeof AdminUsersRoute
  '/kitchen/dietary-notes': typeof KitchenDietaryNotesRoute
  '/kitchen/meal-totals': typeof KitchenMealTotalsRoute
  '/kitchen/preparation': typeof KitchenPreparationRoute
  '/kitchen/reports': typeof KitchenReportsRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/communications': typeof StaffCommunicationsRoute
  '/staff/guest-requests': typeof StaffGuestRequestsRoute
  '/staff/reservations': typeof StaffReservationsRouteWithChildren
  '/staff/seating': typeof StaffSeatingRoute
  '/staff/waitlist': typeof StaffWaitlistRoute
  '/staff/walk-ins': typeof StaffWalkInsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/account/reservations/$reservationId': typeof AccountReservationsReservationIdRoute
  '/staff/reservations/$reservationId': typeof StaffReservationsReservationIdRoute
  '/account/reservations/': typeof AccountReservationsIndexRoute
  '/staff/reservations/': typeof StaffReservationsIndexRoute
}
export interface FileRoutesByTo {
  '/book': typeof PublicBookRoute
  '/contact': typeof PublicContactRoute
  '/create-account': typeof PublicCreateAccountRoute
  '/faq': typeof PublicFaqRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/menu': typeof PublicMenuRoute
  '/our-story': typeof PublicOurStoryRoute
  '/policies': typeof PublicPoliciesRoute
  '/private-room': typeof PublicPrivateRoomRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/the-experience': typeof PublicTheExperienceRoute
  '/waitlist': typeof PublicWaitlistRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/support': typeof AccountSupportRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu-items': typeof AdminMenuItemsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/private-room': typeof AdminPrivateRoomRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seating-times': typeof AdminSeatingTimesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sundays': typeof AdminSundaysRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/admin/users': typeof AdminUsersRoute
  '/kitchen/dietary-notes': typeof KitchenDietaryNotesRoute
  '/kitchen/meal-totals': typeof KitchenMealTotalsRoute
  '/kitchen/preparation': typeof KitchenPreparationRoute
  '/kitchen/reports': typeof KitchenReportsRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/communications': typeof StaffCommunicationsRoute
  '/staff/guest-requests': typeof StaffGuestRequestsRoute
  '/staff/seating': typeof StaffSeatingRoute
  '/staff/waitlist': typeof StaffWaitlistRoute
  '/staff/walk-ins': typeof StaffWalkInsRoute
  '/': typeof PublicIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/staff': typeof StaffIndexRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/account/reservations/$reservationId': typeof AccountReservationsReservationIdRoute
  '/staff/reservations/$reservationId': typeof StaffReservationsReservationIdRoute
  '/account/reservations': typeof AccountReservationsIndexRoute
  '/staff/reservations': typeof StaffReservationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/kitchen': typeof KitchenRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/_public/book': typeof PublicBookRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/create-account': typeof PublicCreateAccountRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/how-it-works': typeof PublicHowItWorksRoute
  '/_public/menu': typeof PublicMenuRoute
  '/_public/our-story': typeof PublicOurStoryRoute
  '/_public/policies': typeof PublicPoliciesRoute
  '/_public/private-room': typeof PublicPrivateRoomRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/the-experience': typeof PublicTheExperienceRoute
  '/_public/waitlist': typeof PublicWaitlistRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRouteWithChildren
  '/account/support': typeof AccountSupportRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/menu-items': typeof AdminMenuItemsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/private-room': typeof AdminPrivateRoomRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seating-times': typeof AdminSeatingTimesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sundays': typeof AdminSundaysRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/taxes': typeof AdminTaxesRoute
  '/admin/users': typeof AdminUsersRoute
  '/kitchen/dietary-notes': typeof KitchenDietaryNotesRoute
  '/kitchen/meal-totals': typeof KitchenMealTotalsRoute
  '/kitchen/preparation': typeof KitchenPreparationRoute
  '/kitchen/reports': typeof KitchenReportsRoute
  '/staff/calendar': typeof StaffCalendarRoute
  '/staff/check-in': typeof StaffCheckInRoute
  '/staff/communications': typeof StaffCommunicationsRoute
  '/staff/guest-requests': typeof StaffGuestRequestsRoute
  '/staff/reservations': typeof StaffReservationsRouteWithChildren
  '/staff/seating': typeof StaffSeatingRoute
  '/staff/waitlist': typeof StaffWaitlistRoute
  '/staff/walk-ins': typeof StaffWalkInsRoute
  '/_public/': typeof PublicIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/_public/auth/callback': typeof PublicAuthCallbackRoute
  '/account/reservations/$reservationId': typeof AccountReservationsReservationIdRoute
  '/staff/reservations/$reservationId': typeof StaffReservationsReservationIdRoute
  '/account/reservations/': typeof AccountReservationsIndexRoute
  '/staff/reservations/': typeof StaffReservationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/kitchen'
    | '/staff'
    | '/book'
    | '/contact'
    | '/create-account'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/menu'
    | '/our-story'
    | '/policies'
    | '/private-room'
    | '/reset-password'
    | '/sign-in'
    | '/the-experience'
    | '/waitlist'
    | '/account/payments'
    | '/account/profile'
    | '/account/reservations'
    | '/account/support'
    | '/admin/audit-log'
    | '/admin/content'
    | '/admin/discounts'
    | '/admin/emails'
    | '/admin/fees'
    | '/admin/integrations'
    | '/admin/media'
    | '/admin/menu-items'
    | '/admin/menus'
    | '/admin/navigation'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/private-room'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/roles'
    | '/admin/seating-times'
    | '/admin/settings'
    | '/admin/sundays'
    | '/admin/tables'
    | '/admin/taxes'
    | '/admin/users'
    | '/kitchen/dietary-notes'
    | '/kitchen/meal-totals'
    | '/kitchen/preparation'
    | '/kitchen/reports'
    | '/staff/calendar'
    | '/staff/check-in'
    | '/staff/communications'
    | '/staff/guest-requests'
    | '/staff/reservations'
    | '/staff/seating'
    | '/staff/waitlist'
    | '/staff/walk-ins'
    | '/account/'
    | '/admin/'
    | '/kitchen/'
    | '/staff/'
    | '/auth/callback'
    | '/account/reservations/$reservationId'
    | '/staff/reservations/$reservationId'
    | '/account/reservations/'
    | '/staff/reservations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/book'
    | '/contact'
    | '/create-account'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/menu'
    | '/our-story'
    | '/policies'
    | '/private-room'
    | '/reset-password'
    | '/sign-in'
    | '/the-experience'
    | '/waitlist'
    | '/account/payments'
    | '/account/profile'
    | '/account/support'
    | '/admin/audit-log'
    | '/admin/content'
    | '/admin/discounts'
    | '/admin/emails'
    | '/admin/fees'
    | '/admin/integrations'
    | '/admin/media'
    | '/admin/menu-items'
    | '/admin/menus'
    | '/admin/navigation'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/private-room'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/roles'
    | '/admin/seating-times'
    | '/admin/settings'
    | '/admin/sundays'
    | '/admin/tables'
    | '/admin/taxes'
    | '/admin/users'
    | '/kitchen/dietary-notes'
    | '/kitchen/meal-totals'
    | '/kitchen/preparation'
    | '/kitchen/reports'
    | '/staff/calendar'
    | '/staff/check-in'
    | '/staff/communications'
    | '/staff/guest-requests'
    | '/staff/seating'
    | '/staff/waitlist'
    | '/staff/walk-ins'
    | '/'
    | '/account'
    | '/admin'
    | '/kitchen'
    | '/staff'
    | '/auth/callback'
    | '/account/reservations/$reservationId'
    | '/staff/reservations/$reservationId'
    | '/account/reservations'
    | '/staff/reservations'
  id:
    | '__root__'
    | '/_public'
    | '/account'
    | '/admin'
    | '/kitchen'
    | '/staff'
    | '/_public/book'
    | '/_public/contact'
    | '/_public/create-account'
    | '/_public/faq'
    | '/_public/forgot-password'
    | '/_public/how-it-works'
    | '/_public/menu'
    | '/_public/our-story'
    | '/_public/policies'
    | '/_public/private-room'
    | '/_public/reset-password'
    | '/_public/sign-in'
    | '/_public/the-experience'
    | '/_public/waitlist'
    | '/account/payments'
    | '/account/profile'
    | '/account/reservations'
    | '/account/support'
    | '/admin/audit-log'
    | '/admin/content'
    | '/admin/discounts'
    | '/admin/emails'
    | '/admin/fees'
    | '/admin/integrations'
    | '/admin/media'
    | '/admin/menu-items'
    | '/admin/menus'
    | '/admin/navigation'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/private-room'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/roles'
    | '/admin/seating-times'
    | '/admin/settings'
    | '/admin/sundays'
    | '/admin/tables'
    | '/admin/taxes'
    | '/admin/users'
    | '/kitchen/dietary-notes'
    | '/kitchen/meal-totals'
    | '/kitchen/preparation'
    | '/kitchen/reports'
    | '/staff/calendar'
    | '/staff/check-in'
    | '/staff/communications'
    | '/staff/guest-requests'
    | '/staff/reservations'
    | '/staff/seating'
    | '/staff/waitlist'
    | '/staff/walk-ins'
    | '/_public/'
    | '/account/'
    | '/admin/'
    | '/kitchen/'
    | '/staff/'
    | '/_public/auth/callback'
    | '/account/reservations/$reservationId'
    | '/staff/reservations/$reservationId'
    | '/account/reservations/'
    | '/staff/reservations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  KitchenRoute: typeof KitchenRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/book': {
      id: '/_public/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof PublicBookRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/create-account': {
      id: '/_public/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof PublicCreateAccountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/how-it-works': {
      id: '/_public/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof PublicHowItWorksRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/menu': {
      id: '/_public/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof PublicMenuRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/our-story': {
      id: '/_public/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof PublicOurStoryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/policies': {
      id: '/_public/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PublicPoliciesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/private-room': {
      id: '/_public/private-room'
      path: '/private-room'
      fullPath: '/private-room'
      preLoaderRoute: typeof PublicPrivateRoomRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/the-experience': {
      id: '/_public/the-experience'
      path: '/the-experience'
      fullPath: '/the-experience'
      preLoaderRoute: typeof PublicTheExperienceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/waitlist': {
      id: '/_public/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof PublicWaitlistRouteImport
      parentRoute: typeof PublicRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reservations': {
      id: '/account/reservations'
      path: '/reservations'
      fullPath: '/account/reservations'
      preLoaderRoute: typeof AccountReservationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-items': {
      id: '/admin/menu-items'
      path: '/menu-items'
      fullPath: '/admin/menu-items'
      preLoaderRoute: typeof AdminMenuItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/private-room': {
      id: '/admin/private-room'
      path: '/private-room'
      fullPath: '/admin/private-room'
      preLoaderRoute: typeof AdminPrivateRoomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seating-times': {
      id: '/admin/seating-times'
      path: '/seating-times'
      fullPath: '/admin/seating-times'
      preLoaderRoute: typeof AdminSeatingTimesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sundays': {
      id: '/admin/sundays'
      path: '/sundays'
      fullPath: '/admin/sundays'
      preLoaderRoute: typeof AdminSundaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxes': {
      id: '/admin/taxes'
      path: '/taxes'
      fullPath: '/admin/taxes'
      preLoaderRoute: typeof AdminTaxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/kitchen/dietary-notes': {
      id: '/kitchen/dietary-notes'
      path: '/dietary-notes'
      fullPath: '/kitchen/dietary-notes'
      preLoaderRoute: typeof KitchenDietaryNotesRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/kitchen/meal-totals': {
      id: '/kitchen/meal-totals'
      path: '/meal-totals'
      fullPath: '/kitchen/meal-totals'
      preLoaderRoute: typeof KitchenMealTotalsRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/kitchen/preparation': {
      id: '/kitchen/preparation'
      path: '/preparation'
      fullPath: '/kitchen/preparation'
      preLoaderRoute: typeof KitchenPreparationRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/kitchen/reports': {
      id: '/kitchen/reports'
      path: '/reports'
      fullPath: '/kitchen/reports'
      preLoaderRoute: typeof KitchenReportsRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/calendar': {
      id: '/staff/calendar'
      path: '/calendar'
      fullPath: '/staff/calendar'
      preLoaderRoute: typeof StaffCalendarRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/check-in': {
      id: '/staff/check-in'
      path: '/check-in'
      fullPath: '/staff/check-in'
      preLoaderRoute: typeof StaffCheckInRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/communications': {
      id: '/staff/communications'
      path: '/communications'
      fullPath: '/staff/communications'
      preLoaderRoute: typeof StaffCommunicationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/guest-requests': {
      id: '/staff/guest-requests'
      path: '/guest-requests'
      fullPath: '/staff/guest-requests'
      preLoaderRoute: typeof StaffGuestRequestsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/reservations': {
      id: '/staff/reservations'
      path: '/reservations'
      fullPath: '/staff/reservations'
      preLoaderRoute: typeof StaffReservationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/seating': {
      id: '/staff/seating'
      path: '/seating'
      fullPath: '/staff/seating'
      preLoaderRoute: typeof StaffSeatingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/waitlist': {
      id: '/staff/waitlist'
      path: '/waitlist'
      fullPath: '/staff/waitlist'
      preLoaderRoute: typeof StaffWaitlistRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/walk-ins': {
      id: '/staff/walk-ins'
      path: '/walk-ins'
      fullPath: '/staff/walk-ins'
      preLoaderRoute: typeof StaffWalkInsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_public/auth/callback': {
      id: '/_public/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof PublicAuthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/account/reservations/': {
      id: '/account/reservations/'
      path: '/'
      fullPath: '/account/reservations/'
      preLoaderRoute: typeof AccountReservationsIndexRouteImport
      parentRoute: typeof AccountReservationsRoute
    }
    '/account/reservations/$reservationId': {
      id: '/account/reservations/$reservationId'
      path: '/$reservationId'
      fullPath: '/account/reservations/$reservationId'
      preLoaderRoute: typeof AccountReservationsReservationIdRouteImport
      parentRoute: typeof AccountReservationsRoute
    }
    '/staff/reservations/': {
      id: '/staff/reservations/'
      path: '/'
      fullPath: '/staff/reservations/'
      preLoaderRoute: typeof StaffReservationsIndexRouteImport
      parentRoute: typeof StaffReservationsRoute
    }
    '/staff/reservations/$reservationId': {
      id: '/staff/reservations/$reservationId'
      path: '/$reservationId'
      fullPath: '/staff/reservations/$reservationId'
      preLoaderRoute: typeof StaffReservationsReservationIdRouteImport
      parentRoute: typeof StaffReservationsRoute
    }
  }
}

interface PublicRouteChildren {
  PublicBookRoute: typeof PublicBookRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCreateAccountRoute: typeof PublicCreateAccountRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicHowItWorksRoute: typeof PublicHowItWorksRoute
  PublicMenuRoute: typeof PublicMenuRoute
  PublicOurStoryRoute: typeof PublicOurStoryRoute
  PublicPoliciesRoute: typeof PublicPoliciesRoute
  PublicPrivateRoomRoute: typeof PublicPrivateRoomRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicTheExperienceRoute: typeof PublicTheExperienceRoute
  PublicWaitlistRoute: typeof PublicWaitlistRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthCallbackRoute: typeof PublicAuthCallbackRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBookRoute: PublicBookRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCreateAccountRoute: PublicCreateAccountRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicHowItWorksRoute: PublicHowItWorksRoute,
  PublicMenuRoute: PublicMenuRoute,
  PublicOurStoryRoute: PublicOurStoryRoute,
  PublicPoliciesRoute: PublicPoliciesRoute,
  PublicPrivateRoomRoute: PublicPrivateRoomRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicTheExperienceRoute: PublicTheExperienceRoute,
  PublicWaitlistRoute: PublicWaitlistRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthCallbackRoute: PublicAuthCallbackRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AccountReservationsRouteChildren {
  AccountReservationsReservationIdRoute: typeof AccountReservationsReservationIdRoute
  AccountReservationsIndexRoute: typeof AccountReservationsIndexRoute
}

const AccountReservationsRouteChildren: AccountReservationsRouteChildren = {
  AccountReservationsReservationIdRoute: AccountReservationsReservationIdRoute,
  AccountReservationsIndexRoute: AccountReservationsIndexRoute,
}

const AccountReservationsRouteWithChildren =
  AccountReservationsRoute._addFileChildren(AccountReservationsRouteChildren)

interface AccountRouteChildren {
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReservationsRoute: typeof AccountReservationsRouteWithChildren
  AccountSupportRoute: typeof AccountSupportRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReservationsRoute: AccountReservationsRouteWithChildren,
  AccountSupportRoute: AccountSupportRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMenuItemsRoute: typeof AdminMenuItemsRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminPrivateRoomRoute: typeof AdminPrivateRoomRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSeatingTimesRoute: typeof AdminSeatingTimesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSundaysRoute: typeof AdminSundaysRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminTaxesRoute: typeof AdminTaxesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMenuItemsRoute: AdminMenuItemsRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminPrivateRoomRoute: AdminPrivateRoomRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSeatingTimesRoute: AdminSeatingTimesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSundaysRoute: AdminSundaysRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminTaxesRoute: AdminTaxesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KitchenRouteChildren {
  KitchenDietaryNotesRoute: typeof KitchenDietaryNotesRoute
  KitchenMealTotalsRoute: typeof KitchenMealTotalsRoute
  KitchenPreparationRoute: typeof KitchenPreparationRoute
  KitchenReportsRoute: typeof KitchenReportsRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
}

const KitchenRouteChildren: KitchenRouteChildren = {
  KitchenDietaryNotesRoute: KitchenDietaryNotesRoute,
  KitchenMealTotalsRoute: KitchenMealTotalsRoute,
  KitchenPreparationRoute: KitchenPreparationRoute,
  KitchenReportsRoute: KitchenReportsRoute,
  KitchenIndexRoute: KitchenIndexRoute,
}

const KitchenRouteWithChildren =
  KitchenRoute._addFileChildren(KitchenRouteChildren)

interface StaffReservationsRouteChildren {
  StaffReservationsReservationIdRoute: typeof StaffReservationsReservationIdRoute
  StaffReservationsIndexRoute: typeof StaffReservationsIndexRoute
}

const StaffReservationsRouteChildren: StaffReservationsRouteChildren = {
  StaffReservationsReservationIdRoute: StaffReservationsReservationIdRoute,
  StaffReservationsIndexRoute: StaffReservationsIndexRoute,
}

const StaffReservationsRouteWithChildren =
  StaffReservationsRoute._addFileChildren(StaffReservationsRouteChildren)

interface StaffRouteChildren {
  StaffCalendarRoute: typeof StaffCalendarRoute
  StaffCheckInRoute: typeof StaffCheckInRoute
  StaffCommunicationsRoute: typeof StaffCommunicationsRoute
  StaffGuestRequestsRoute: typeof StaffGuestRequestsRoute
  StaffReservationsRoute: typeof StaffReservationsRouteWithChildren
  StaffSeatingRoute: typeof StaffSeatingRoute
  StaffWaitlistRoute: typeof StaffWaitlistRoute
  StaffWalkInsRoute: typeof StaffWalkInsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCalendarRoute: StaffCalendarRoute,
  StaffCheckInRoute: StaffCheckInRoute,
  StaffCommunicationsRoute: StaffCommunicationsRoute,
  StaffGuestRequestsRoute: StaffGuestRequestsRoute,
  StaffReservationsRoute: StaffReservationsRouteWithChildren,
  StaffSeatingRoute: StaffSeatingRoute,
  StaffWaitlistRoute: StaffWaitlistRoute,
  StaffWalkInsRoute: StaffWalkInsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  KitchenRoute: KitchenRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
